// 曲库：带分类、难度、时值、BPM 等完整元数据
export type SongCategory = 'nursery' | 'classic' | 'folk' | 'festival' | 'custom'

export interface MelodyNote {
  /** 科学音高记号，如 C4；'rest' 表示休止符 */
  note: string
  /** 时值（拍数），1=四分音符，0.5=八分，2=二分 */
  beats: number
}

export interface Song {
  id: string
  title: string
  category: SongCategory
  /** 难度 1..5 */
  level: number
  /** 每分钟拍数 */
  bpm: number
  /** 拍号分子，如 4（4/4） */
  beatsPerBar: number
  /** 旋律 */
  melody: MelodyNote[]
  /** 是否自定义 */
  custom?: boolean
  /** 简介 */
  desc?: string
  /** 伴奏和弦进行（每项为一个小节的和弦根音+性质），可选。缺省时引擎自动按旋律推断 */
  chords?: { root: string; quality: 'maj' | 'min' }[]
  /** 歌词（传统/民歌曲目；版权曲目省略），按乐句用 \n 分行 */
  lyrics?: string
  /** 关联的乐理主题 id，可在乐理页与曲库间互相跳转 */
  relatedTopics?: string[]
}

export const CATEGORY_INFO: Record<SongCategory, { name: string; icon: string; color: string }> = {
  nursery: { name: '儿歌童谣', icon: '🧸', color: '#ff922b' },
  classic: { name: '古典名曲', icon: '🎻', color: '#845ef7' },
  folk: { name: '民歌民乐', icon: '🏮', color: '#e64980' },
  festival: { name: '节日歌曲', icon: '🎉', color: '#20c997' },
  custom: { name: '我的创作', icon: '✏️', color: '#4dabf7' },
}

// 便捷构造：等时值旋律
function seq(notes: string[], beats = 1): MelodyNote[] {
  return notes.map((note) => ({ note, beats }))
}

export const BUILTIN_SONGS: Song[] = [
  {
    id: 'twinkle',
    title: '小星星',
    category: 'nursery',
    level: 1,
    bpm: 100,
    beatsPerBar: 4,
    desc: '经典入门儿歌，全白键',
    melody: seq(['C4', 'C4', 'G4', 'G4', 'A4', 'A4', 'G4', 'F4', 'F4', 'E4', 'E4', 'D4', 'D4', 'C4']),
  },
  {
    id: 'mary',
    title: '玛丽有只小羊羔',
    category: 'nursery',
    level: 1,
    bpm: 100,
    beatsPerBar: 4,
    desc: '旋律简单，适合初学',
    melody: seq(['E4', 'D4', 'C4', 'D4', 'E4', 'E4', 'E4', 'D4', 'D4', 'D4', 'E4', 'G4', 'G4']),
  },
  {
    id: 'rowboat',
    title: '划船歌',
    category: 'nursery',
    level: 1,
    bpm: 90,
    beatsPerBar: 3,
    desc: 'Row Row Row Your Boat',
    melody: seq(['C4', 'C4', 'C4', 'D4', 'E4', 'E4', 'D4', 'E4', 'F4', 'G4']),
  },
  {
    id: 'bus',
    title: '公车轮子转呀转',
    category: 'nursery',
    level: 2,
    bpm: 110,
    beatsPerBar: 4,
    desc: 'The Wheels on the Bus',
    melody: seq(['C4', 'F4', 'F4', 'F4', 'A4', 'C5', 'A4', 'F4', 'G4', 'E4', 'C4']),
  },
  {
    id: 'ode',
    title: '欢乐颂',
    category: 'classic',
    level: 2,
    bpm: 120,
    beatsPerBar: 4,
    desc: '贝多芬第九交响曲',
    melody: seq([
      'E4', 'E4', 'F4', 'G4', 'G4', 'F4', 'E4', 'D4', 'C4', 'C4', 'D4', 'E4', 'E4', 'D4', 'D4',
    ]),
  },
  {
    id: 'minuet',
    title: '小步舞曲',
    category: 'classic',
    level: 3,
    bpm: 120,
    beatsPerBar: 3,
    desc: '巴赫',
    melody: seq(['D5', 'G4', 'A4', 'B4', 'C5', 'D5', 'G4', 'G4', 'E5', 'C5', 'D5', 'E5', 'F5', 'G5', 'G4', 'G4']),
  },
  {
    id: 'canon',
    title: '卡农',
    category: 'classic',
    level: 4,
    bpm: 90,
    beatsPerBar: 4,
    desc: '帕赫贝尔',
    melody: seq(['E5', 'D5', 'C5', 'B4', 'A4', 'G4', 'A4', 'B4', 'C5', 'B4', 'A4', 'G4', 'F4', 'E4', 'F4', 'G4']),
  },
  {
    id: 'jasmine',
    title: '茉莉花',
    category: 'folk',
    level: 3,
    bpm: 80,
    beatsPerBar: 4,
    desc: '中国民歌',
    melody: seq(['E4', 'E4', 'G4', 'A4', 'C5', 'C5', 'A4', 'G4', 'A4', 'G4', 'E4', 'D4', 'E4']),
  },
  {
    id: 'kanding',
    title: '康定情歌',
    category: 'folk',
    level: 2,
    bpm: 90,
    beatsPerBar: 4,
    desc: '四川民歌',
    melody: seq(['G4', 'G4', 'A4', 'G4', 'E4', 'G4', 'A4', 'C5', 'A4', 'G4', 'E4', 'D4']),
  },
  {
    id: 'jingle',
    title: '铃儿响叮当',
    category: 'festival',
    level: 2,
    bpm: 120,
    beatsPerBar: 4,
    desc: 'Jingle Bells',
    melody: seq(['E4', 'E4', 'E4', 'E4', 'E4', 'E4', 'E4', 'G4', 'C4', 'D4', 'E4']),
  },
  {
    id: 'happybirthday',
    title: '生日快乐',
    category: 'festival',
    level: 2,
    bpm: 110,
    beatsPerBar: 3,
    desc: 'Happy Birthday',
    melody: [
      { note: 'C4', beats: 0.75 }, { note: 'C4', beats: 0.25 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'E4', beats: 2 },
      { note: 'C4', beats: 0.75 }, { note: 'C4', beats: 0.25 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'F4', beats: 2 },
    ],
  },
  {
    id: 'scale',
    title: 'C大调音阶',
    category: 'classic',
    level: 1,
    bpm: 100,
    beatsPerBar: 4,
    desc: '基础音阶练习',
    melody: seq(['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5', 'B4', 'A4', 'G4', 'F4', 'E4', 'D4', 'C4']),
  },
  {
    id: 'twolittle-tigers',
    title: '两只老虎',
    category: 'nursery',
    level: 1,
    bpm: 110,
    beatsPerBar: 4,
    desc: '经典轮唱儿歌',
    melody: seq(['C4', 'D4', 'E4', 'C4', 'C4', 'D4', 'E4', 'C4', 'E4', 'F4', 'G4', 'E4', 'F4', 'G4']),
  },
  {
    id: 'london-bridge',
    title: '伦敦大桥',
    category: 'nursery',
    level: 1,
    bpm: 110,
    beatsPerBar: 4,
    desc: 'London Bridge',
    melody: seq(['G4', 'A4', 'G4', 'F4', 'E4', 'F4', 'G4', 'D4', 'E4', 'F4', 'E4', 'F4', 'G4']),
  },
  {
    id: 'abablacksheep',
    title: '咩咩黑羊',
    category: 'nursery',
    level: 1,
    bpm: 100,
    beatsPerBar: 4,
    desc: 'Baa Baa Black Sheep',
    melody: seq(['C4', 'C4', 'G4', 'G4', 'A4', 'B4', 'C5', 'A4', 'G4']),
  },
  {
    id: 'ifyoure-happy',
    title: '如果感到幸福你就拍拍手',
    category: 'nursery',
    level: 2,
    bpm: 120,
    beatsPerBar: 4,
    desc: '欢快互动儿歌',
    melody: seq(['C4', 'F4', 'F4', 'F4', 'F4', 'E4', 'F4', 'G4', 'F4', 'C4', 'C4']),
  },
  {
    id: 'do-re-mi',
    title: 'Do-Re-Mi',
    category: 'classic',
    level: 2,
    bpm: 120,
    beatsPerBar: 4,
    desc: '音乐之声',
    melody: seq(['C4', 'D4', 'E4', 'C4', 'E4', 'C4', 'E4', 'D4', 'E4', 'F4', 'F4', 'E4', 'D4', 'F4']),
  },
  {
    id: 'aura-lee',
    title: '奥拉李',
    category: 'classic',
    level: 3,
    bpm: 90,
    beatsPerBar: 4,
    desc: 'Aura Lee（猫王名曲原型）',
    melody: seq(['G4', 'A4', 'B4', 'C5', 'B4', 'A4', 'G4', 'A4', 'B4', 'A4', 'G4', 'F4', 'G4']),
  },
  {
    id: 'surprise',
    title: '惊愕交响曲',
    category: 'classic',
    level: 3,
    bpm: 100,
    beatsPerBar: 4,
    desc: '海顿',
    melody: seq(['C4', 'C4', 'E4', 'E4', 'G4', 'G4', 'E4', 'F4', 'F4', 'D4', 'D4', 'B4', 'B4', 'C5']),
  },
  {
    id: 'moon-river',
    title: '茉莉花开（民乐）',
    category: 'folk',
    level: 3,
    bpm: 75,
    beatsPerBar: 4,
    desc: '民乐五声风',
    melody: seq(['C4', 'D4', 'E4', 'G4', 'A4', 'G4', 'E4', 'D4', 'C4', 'D4', 'E4', 'C4']),
  },
  {
    id: 'colorful-clouds',
    title: '彩云追月',
    category: 'folk',
    level: 4,
    bpm: 80,
    beatsPerBar: 4,
    desc: '广东音乐',
    melody: seq(['G4', 'A4', 'C5', 'A4', 'G4', 'E4', 'G4', 'A4', 'G4', 'E4', 'D4', 'E4', 'C4']),
  },
  {
    id: 'edelweiss',
    title: '雪绒花',
    category: 'festival',
    level: 3,
    bpm: 90,
    beatsPerBar: 3,
    desc: 'Edelweiss',
    melody: seq(['C4', 'G4', 'F4', 'G4', 'E4', 'C4', 'C4', 'D4', 'E4', 'F4', 'G4', 'G4']),
  },
  {
    id: 'we-wish',
    title: '祝你圣诞快乐',
    category: 'festival',
    level: 2,
    bpm: 120,
    beatsPerBar: 3,
    desc: 'We Wish You a Merry Christmas',
    melody: seq(['C4', 'F4', 'F4', 'G4', 'F4', 'E4', 'D4', 'D4', 'D4', 'G4', 'G4', 'A4', 'G4', 'F4', 'E4']),
  },
  {
    id: 'auld-lang',
    title: '友谊地久天长',
    category: 'festival',
    level: 3,
    bpm: 90,
    beatsPerBar: 4,
    desc: 'Auld Lang Syne',
    melody: seq(['C4', 'F4', 'F4', 'F4', 'A4', 'G4', 'F4', 'G4', 'A4', 'G4', 'F4', 'F4', 'A4', 'C5', 'C5']),
  },
  {
    id: 'little-bee',
    title: '小蜜蜂',
    category: 'nursery',
    level: 1,
    bpm: 110,
    beatsPerBar: 2,
    desc: '嗡嗡嗡，采蜜忙',
    melody: seq(['G4', 'E4', 'E4', 'F4', 'D4', 'D4', 'C4', 'D4', 'E4', 'F4', 'G4', 'G4', 'G4']),
  },
  {
    id: 'counting-ducks',
    title: '数鸭子',
    category: 'nursery',
    level: 2,
    bpm: 120,
    beatsPerBar: 2,
    desc: '门前大桥下游过一群鸭',
    melody: seq(['C4', 'C4', 'C4', 'D4', 'E4', 'C4', 'E4', 'E4', 'D4', 'C4', 'D4', 'E4', 'C4']),
  },
  {
    id: 'grandma-bridge',
    title: '摇到外婆桥',
    category: 'nursery',
    level: 1,
    bpm: 90,
    beatsPerBar: 4,
    desc: '摇啊摇',
    melody: seq(['E4', 'G4', 'A4', 'G4', 'E4', 'D4', 'C4', 'D4', 'E4', 'G4', 'E4']),
  },
  {
    id: 'spring-buds',
    title: '春天在哪里',
    category: 'nursery',
    level: 2,
    bpm: 120,
    beatsPerBar: 4,
    desc: '春天在那青翠的山林里',
    melody: seq(['C4', 'E4', 'G4', 'G4', 'A4', 'G4', 'E4', 'C4', 'D4', 'E4', 'D4', 'C4']),
  },
  {
    id: 'clementine',
    title: '我的邦妮',
    category: 'classic',
    level: 2,
    bpm: 100,
    beatsPerBar: 3,
    desc: 'My Bonnie',
    melody: seq(['C4', 'F4', 'F4', 'F4', 'A4', 'G4', 'F4', 'E4', 'D4', 'D4', 'E4', 'F4']),
  },
  {
    id: 'greensleeves',
    title: '绿袖子',
    category: 'classic',
    level: 4,
    bpm: 90,
    beatsPerBar: 3,
    desc: 'Greensleeves（英国民谣）',
    melody: seq(['A4', 'C5', 'D5', 'E5', 'F5', 'E5', 'D5', 'B4', 'G4', 'A4', 'B4', 'C5', 'A4', 'A4', 'G4', 'A4']),
  },
  {
    id: 'swan-lake',
    title: '天鹅湖主题',
    category: 'classic',
    level: 4,
    bpm: 90,
    beatsPerBar: 4,
    desc: '柴可夫斯基',
    melody: seq(['B4', 'E5', 'G5', 'F5', 'E5', 'B5', 'A5', 'A5', 'A5', 'F5', 'F5', 'E5']),
  },
  {
    id: 'song-of-joy',
    title: '送别',
    category: 'folk',
    level: 3,
    bpm: 75,
    beatsPerBar: 4,
    desc: '长亭外，古道边',
    melody: seq(['G4', 'C5', 'C5', 'B4', 'C5', 'E5', 'D5', 'C5', 'C5', 'A4', 'G4', 'G4']),
  },
  {
    id: 'in-that-place',
    title: '在那遥远的地方',
    category: 'folk',
    level: 3,
    bpm: 80,
    beatsPerBar: 4,
    desc: '西部民歌',
    melody: seq(['G4', 'G4', 'A4', 'G4', 'E4', 'G4', 'C5', 'A4', 'G4', 'E4', 'D4', 'C4']),
  },
  {
    id: 'colorful-yunnan',
    title: '小放牛',
    category: 'folk',
    level: 2,
    bpm: 100,
    beatsPerBar: 2,
    desc: '河北民歌',
    melody: seq(['C4', 'D4', 'E4', 'G4', 'A4', 'G4', 'E4', 'G4', 'A4', 'C5', 'A4', 'G4']),
  },
  {
    id: 'happy-newyear',
    title: '新年好',
    category: 'festival',
    level: 1,
    bpm: 110,
    beatsPerBar: 4,
    desc: '新年好呀，新年好呀',
    melody: seq(['C4', 'C4', 'C4', 'G3', 'E4', 'E4', 'E4', 'C4', 'C4', 'E4', 'G4', 'G4', 'F4', 'E4', 'D4']),
  },
  {
    id: 'lantern',
    title: '卖汤圆',
    category: 'festival',
    level: 2,
    bpm: 120,
    beatsPerBar: 4,
    desc: '卖汤圆，卖汤圆',
    melody: seq(['G4', 'G4', 'A4', 'G4', 'E4', 'G4', 'C5', 'C5', 'A4', 'G4', 'E4', 'G4']),
  },
]
