// 曲库：带分类、难度、时值、BPM 等完整元数据
export type SongCategory = 'nursery' | 'classic' | 'folk' | 'festival' | 'custom'

export interface MelodyNote {
  /** 科学音高记号，如 C4；'rest' 表示休止符 */
  note: string
  /** 时值（拍数），1=四分音符，0.5=八分，2=二分 */
  beats: number
}

export interface Song {
  id: string
  title: string
  category: SongCategory
  /** 难度 1..5 */
  level: number
  /** 每分钟拍数 */
  bpm: number
  /** 拍号分子，如 4（4/4） */
  beatsPerBar: number
  /** 旋律 */
  melody: MelodyNote[]
  /** 是否自定义 */
  custom?: boolean
  /** 简介 */
  desc?: string
  /** 伴奏和弦进行（每项为一个小节的和弦根音+性质），可选。缺省时引擎自动按旋律推断 */
  chords?: { root: string; quality: 'maj' | 'min' }[]
  /** 歌词（传统/民歌曲目；版权曲目省略），按乐句用 \n 分行 */
  lyrics?: string
  /** 关联的乐理主题 id，可在乐理页与曲库之间互相跳转 */
  relatedTopics?: string[]
}

export const CATEGORY_INFO: Record<SongCategory, { name: string; icon: string; color: string }> = {
  nursery: { name: '儿歌童谣', icon: '🧸', color: '#ff922b' },
  classic: { name: '古典名曲', icon: '🎻', color: '#845ef7' },
  folk: { name: '民歌民乐', icon: '🏮', color: '#e64980' },
  festival: { name: '节日歌曲', icon: '🎉', color: '#20c997' },
  custom: { name: '我的创作', icon: '✏️', color: '#4dabf7' },
}

export const BUILTIN_SONGS: Song[] = [
  {
    id: 'twinkle',
    title: '小星星',
    category: 'nursery',
    level: 1,
    bpm: 100,
    beatsPerBar: 4,
    desc: '法国童谣，全白键入门首选',
    melody: [
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 2 },
      { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 2 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 2 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 2 },
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 2 },
      { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 2 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'F4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '一闪一闪亮晶晶\n满天都是小星星\n挂在天上放光明\n好像许多小眼睛\n一闪一闪亮晶晶\n满天都是小星星',
    relatedTopics: ['c-major-scale', 'quarter-eighth-notes', 'steady-beat'],
  },
  {
    id: 'mary',
    title: '玛丽有只小羊羔',
    category: 'nursery',
    level: 1,
    bpm: 100,
    beatsPerBar: 4,
    desc: '美国童谣，只用 E D C G 四个音',
    melody: [
      { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 2 },
      { note: 'D4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'D4', beats: 2 },
      { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'G4', beats: 2 },
      { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 3 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '玛丽有只小羊羔\n小羊羔 小羊羔\n玛丽有只小羊羔\n雪白毛儿真可爱',
    relatedTopics: ['quarter-eighth-notes', 'pitch-up-down', 'melody-ending'],
  },
  {
    id: 'rowboat',
    title: '划船歌',
    category: 'nursery',
    level: 1,
    bpm: 90,
    beatsPerBar: 3,
    desc: 'Row Row Row Your Boat，三拍摇荡律动',
    melody: [
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'C4', beats: 0.5 }, { note: 'D4', beats: 0.5 },
      { note: 'E4', beats: 1.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 0.5 },
      { note: 'F4', beats: 0.5 }, { note: 'G4', beats: 2.5 },
      { note: 'C5', beats: 0.5 }, { note: 'C5', beats: 0.5 }, { note: 'C5', beats: 0.5 },
      { note: 'G4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'G4', beats: 0.5 },
      { note: 'E4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'E4', beats: 0.5 },
      { note: 'C4', beats: 0.5 }, { note: 'C4', beats: 0.5 }, { note: 'C4', beats: 0.5 },
      { note: 'G4', beats: 0.5 }, { note: 'F4', beats: 0.5 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 2.5 }, { note: 'rest', beats: 0.5 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' },
    ],
    lyrics: '划呀 划呀 划小船\n顺着流水向前\n快快乐乐向前划\n生活像梦境一般',
    relatedTopics: ['meter-basic', 'dotted-rhythm', 'same-note-octave'],
  },
  {
    id: 'bus',
    title: '公车轮子转呀转',
    category: 'nursery',
    level: 2,
    bpm: 110,
    beatsPerBar: 4,
    desc: 'The Wheels on the Bus，附点节奏像车轮滚动',
    melody: [
      { note: 'rest', beats: 1.5 },
      { note: 'C4', beats: 0.5 },
      { note: 'F4', beats: 1.5 }, { note: 'F4', beats: 0.5 }, { note: 'F4', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'C4', beats: 1.5 },
      { note: 'rest', beats: 0.5 },
      { note: 'F4', beats: 1.5 }, { note: 'F4', beats: 0.5 }, { note: 'F4', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'C4', beats: 1.5 },
      { note: 'rest', beats: 0.5 },
    ],
    chords: [
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '公车轮子转呀转\n转呀转 转呀转\n公车轮子转呀转\n穿过大街小巷',
    relatedTopics: ['dotted-rhythm', 'offbeat', 'rests-basic'],
  },
  {
    id: 'ode',
    title: '欢乐颂',
    category: 'classic',
    level: 2,
    bpm: 120,
    beatsPerBar: 4,
    desc: '贝多芬《第九交响曲》末乐章主题',
    melody: [
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'E4', beats: 1.5 }, { note: 'D4', beats: 0.5 }, { note: 'D4', beats: 2 },
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 1.5 }, { note: 'C4', beats: 0.5 }, { note: 'C4', beats: 2 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'A4', quality: 'min' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'A4', quality: 'min' }, { root: 'G4', quality: 'maj' },
    ],
    lyrics: '欢乐女神圣洁美丽\n灿烂光芒照大地\n我们心中充满热情\n来到你的圣殿里',
    relatedTopics: ['dotted-rhythm', 'motif', 'c-major-scale'],
  },
  {
    id: 'minuet',
    title: '小步舞曲',
    category: 'classic',
    level: 3,
    bpm: 120,
    beatsPerBar: 3,
    desc: '佩措尔德小步舞曲（旧题巴赫），G 大调宫廷舞曲',
    melody: [
      { note: 'D5', beats: 1 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'C5', beats: 0.5 },
      { note: 'D5', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'E5', beats: 1 }, { note: 'C5', beats: 0.5 }, { note: 'D5', beats: 0.5 }, { note: 'E5', beats: 0.5 }, { note: 'F5', beats: 0.5 },
      { note: 'G5', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'C5', beats: 1 }, { note: 'D5', beats: 0.5 }, { note: 'C5', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'A4', beats: 0.5 },
      { note: 'B4', beats: 1 }, { note: 'C5', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 },
      { note: 'F5', beats: 1.5 }, { note: 'D5', beats: 0.5 }, { note: 'B4', beats: 1 },
      { note: 'A4', beats: 1.5 }, { note: 'B4', beats: 0.5 }, { note: 'C5', beats: 1 },
      { note: 'D5', beats: 1 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'C5', beats: 0.5 },
      { note: 'D5', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'E5', beats: 1 }, { note: 'C5', beats: 0.5 }, { note: 'D5', beats: 0.5 }, { note: 'E5', beats: 0.5 }, { note: 'F5', beats: 0.5 },
      { note: 'G5', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'B4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'C5', beats: 0.5 },
      { note: 'D5', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'B4', beats: 1 },
      { note: 'A4', beats: 2 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'G4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'D4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'D4', quality: 'maj' },
      { root: 'G4', quality: 'maj' },
    ],
    relatedTopics: ['meter-basic', 'g-major-scale', 'binary-ternary-form'],
  },
  {
    id: 'canon',
    title: '卡农',
    category: 'classic',
    level: 4,
    bpm: 90,
    beatsPerBar: 4,
    desc: '帕赫贝尔《D 大调卡农》主题，固定低音上的八小节模仿',
    melody: [
      { note: 'F5', beats: 2 }, { note: 'E5', beats: 2 },
      { note: 'D5', beats: 2 }, { note: 'C5', beats: 2 },
      { note: 'B4', beats: 2 }, { note: 'A4', beats: 2 },
      { note: 'B4', beats: 2 }, { note: 'C5', beats: 2 },
      { note: 'F5', beats: 0.5 }, { note: 'E5', beats: 0.5 }, { note: 'D5', beats: 0.5 }, { note: 'C5', beats: 0.5 },
      { note: 'B4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'C5', beats: 0.5 },
      { note: 'D5', beats: 0.5 }, { note: 'C5', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'A4', beats: 0.5 },
      { note: 'G4', beats: 0.5 }, { note: 'F4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 },
      { note: 'B4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'F4', beats: 0.5 },
      { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'F4', beats: 0.5 },
      { note: 'G4', beats: 0.5 }, { note: 'F4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 0.5 },
      { note: 'C4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 0.5 }, { note: 'F4', beats: 0.5 },
      { note: 'E5', beats: 1 }, { note: 'D5', beats: 0.5 }, { note: 'C5', beats: 0.5 },
      { note: 'B4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'C5', beats: 0.5 },
      { note: 'D5', beats: 0.5 }, { note: 'C5', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'A4', beats: 0.5 },
      { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'G4', beats: 0.5 },
      { note: 'A4', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'C5', beats: 0.5 }, { note: 'A4', beats: 0.5 },
      { note: 'B4', beats: 0.5 }, { note: 'C5', beats: 0.5 }, { note: 'D5', beats: 0.5 }, { note: 'B4', beats: 0.5 },
      { note: 'C5', beats: 0.5 }, { note: 'D5', beats: 0.5 }, { note: 'E5', beats: 0.5 }, { note: 'C5', beats: 0.5 },
      { note: 'D5', beats: 2 },
    ],
    chords: [
      { root: 'F4', quality: 'maj' }, { root: 'E4', quality: 'min' },
      { root: 'D4', quality: 'min' }, { root: 'C4', quality: 'maj' },
      { root: 'B4', quality: 'min' }, { root: 'A4', quality: 'min' },
      { root: 'G4', quality: 'maj' }, { root: 'A4', quality: 'min' },
      { root: 'B4', quality: 'min' }, { root: 'A4', quality: 'min' },
      { root: 'G4', quality: 'maj' }, { root: 'A4', quality: 'min' },
    ],
    relatedTopics: ['sequence-melodic', 'ostinato', 'broken-chord'],
  },
  {
    id: 'jasmine',
    title: '茉莉花',
    category: 'folk',
    level: 3,
    bpm: 80,
    beatsPerBar: 4,
    desc: '江苏民歌，五声调式的东方韵味',
    melody: [
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 1.5 }, { note: 'C5', beats: 0.5 },
      { note: 'C5', beats: 1 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 2 },
      { note: 'G4', beats: 1 }, { note: 'A4', beats: 0.5 }, { note: 'C5', beats: 0.5 }, { note: 'A4', beats: 1.5 }, { note: 'G4', beats: 0.5 },
      { note: 'A4', beats: 1 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 0.5 }, { note: 'C4', beats: 0.5 }, { note: 'D4', beats: 2 },
      { note: 'D4', beats: 1 }, { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1.5 }, { note: 'D4', beats: 0.5 },
      { note: 'E4', beats: 1 }, { note: 'D4', beats: 0.5 }, { note: 'C4', beats: 0.5 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'A3', beats: 0.5 }, { note: 'C4', beats: 0.5 }, { note: 'A3', beats: 0.5 }, { note: 'G3', beats: 0.5 }, { note: 'A3', beats: 2 },
      { note: 'rest', beats: 4 },
    ],
    chords: [
      { root: 'A3', quality: 'min' }, { root: 'G4', quality: 'maj' },
      { root: 'A3', quality: 'min' }, { root: 'A3', quality: 'min' },
      { root: 'E4', quality: 'min' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'A3', quality: 'min' },
      { root: 'A3', quality: 'min' }, { root: 'A3', quality: 'min' },
    ],
    lyrics: '好一朵美丽的茉莉花\n好一朵美丽的茉莉花\n芬芳美丽满枝桠\n又香又白人人夸\n让我来将你摘下\n送给别人家\n茉莉花呀茉莉花',
    relatedTopics: ['pentatonic-scale', 'gong-shang-jue-zhi-yu', 'folk-song-region'],
  },
  {
    id: 'kanding',
    title: '康定情歌',
    category: 'folk',
    level: 2,
    bpm: 90,
    beatsPerBar: 4,
    desc: '四川民歌《跑马溜溜的山上》',
    melody: [
      { note: 'rest', beats: 3.5 },
      { note: 'G4', beats: 0.5 },
      { note: 'A4', beats: 1.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 },
      { note: 'C5', beats: 2 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 },
      { note: 'G4', beats: 1.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 0.5 },
      { note: 'E4', beats: 2 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 0.5 }, { note: 'D4', beats: 0.5 },
      { note: 'C4', beats: 2 }, { note: 'rest', beats: 1.5 }, { note: 'C4', beats: 0.5 },
      { note: 'D4', beats: 1.5 }, { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'C5', beats: 2 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 },
      { note: 'G4', beats: 1.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 0.5 },
      { note: 'C4', beats: 3 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'A3', quality: 'min' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'A3', quality: 'min' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '跑马溜溜的山上\n一朵溜溜的云哟\n端端溜溜的照在\n康定溜溜的城哟',
    relatedTopics: ['dotted-rhythm', 'pentatonic-scale', 'folk-song-region'],
  },
  {
    id: 'jingle',
    title: '铃儿响叮当',
    category: 'festival',
    level: 2,
    bpm: 120,
    beatsPerBar: 4,
    desc: 'Jingle Bells，副歌雪橇铃铛般的节奏',
    melody: [
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 2 },
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 2 },
      { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'C4', beats: 1.5 }, { note: 'D4', beats: 0.5 },
      { note: 'E4', beats: 3 }, { note: 'rest', beats: 1 },
      { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'F4', beats: 1.5 }, { note: 'F4', beats: 0.5 },
      { note: 'F4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 0.5 }, { note: 'E4', beats: 0.5 },
      { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 2 }, { note: 'G4', beats: 2 },
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 2 },
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 2 },
      { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'C4', beats: 1.5 }, { note: 'D4', beats: 0.5 },
      { note: 'E4', beats: 3 }, { note: 'rest', beats: 1 },
      { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'F4', beats: 1.5 }, { note: 'F4', beats: 0.5 },
      { note: 'F4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 0.5 }, { note: 'E4', beats: 0.5 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 3 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '叮叮当 叮叮当\n铃儿响叮当\n我们滑雪多快乐\n我们坐在雪橇上\n叮叮当 叮叮当\n铃儿响叮当\n冲破大风雪\n我们坐在雪橇上',
    relatedTopics: ['dotted-rhythm', 'rests-basic', 'repeat-signs'],
  },
  {
    id: 'happybirthday',
    title: '生日快乐',
    category: 'festival',
    level: 2,
    bpm: 110,
    beatsPerBar: 3,
    desc: 'Happy Birthday，弱起拍开始的三拍子祝福歌',
    melody: [
      { note: 'rest', beats: 2.75 },
      { note: 'G4', beats: 0.25 },
      { note: 'A4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'B4', beats: 2 }, { note: 'rest', beats: 0.75 }, { note: 'G4', beats: 0.25 },
      { note: 'A4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'D5', beats: 1 },
      { note: 'C5', beats: 2 }, { note: 'rest', beats: 0.75 }, { note: 'G4', beats: 0.25 },
      { note: 'G5', beats: 1 }, { note: 'E5', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'B4', beats: 1 }, { note: 'A4', beats: 1.75 }, { note: 'F5', beats: 0.25 },
      { note: 'E5', beats: 1 }, { note: 'C5', beats: 1 }, { note: 'D5', beats: 1 },
      { note: 'C5', beats: 2 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' },
    ],
    lyrics: '祝你生日快乐\n祝你生日快乐\n祝你生日快乐\n祝你生日快乐',
    relatedTopics: ['offbeat', 'dotted-rhythm', 'meter-basic'],
  },
  {
    id: 'scale',
    title: 'C大调音阶',
    category: 'classic',
    level: 1,
    bpm: 100,
    beatsPerBar: 4,
    desc: 'C 大调音阶上下行练习，全白键',
    melody: [
      { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'B4', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'C5', beats: 1 }, { note: 'B4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'F4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'C4', beats: 0.5 }, { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'F4', beats: 0.5 },
      { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'C5', beats: 0.5 },
      { note: 'C5', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 },
      { note: 'F4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 0.5 }, { note: 'C4', beats: 0.5 },
      { note: 'C4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'C5', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'C4', beats: 4 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'F4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'F4', quality: 'maj' },
      { root: 'C4', quality: 'maj' },
    ],
    relatedTopics: ['c-major-scale', 'whole-half-steps', 'quarter-eighth-notes'],
  },
  {
    id: 'twolittle-tigers',
    title: '两只老虎',
    category: 'nursery',
    level: 1,
    bpm: 110,
    beatsPerBar: 4,
    desc: '法国童谣《雅克兄弟》曲调，经典轮唱曲',
    melody: [
      { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'G4', beats: 2 },
      { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'G4', beats: 2 },
      { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'F4', beats: 0.5 },
      { note: 'E4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'F4', beats: 0.5 },
      { note: 'E4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'C4', beats: 2 },
      { note: 'C4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'C4', beats: 2 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '两只老虎 两只老虎\n跑得快 跑得快\n一只没有耳朵\n一只没有尾巴\n真奇怪 真奇怪',
    relatedTopics: ['quarter-eighth-notes', 'call-response', 'melody-contour'],
  },
  {
    id: 'london-bridge',
    title: '伦敦大桥',
    category: 'nursery',
    level: 1,
    bpm: 110,
    beatsPerBar: 4,
    desc: 'London Bridge Is Falling Down，英国民谣',
    melody: [
      { note: 'G4', beats: 1.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'G4', beats: 2 },
      { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'F4', beats: 2 },
      { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'G4', beats: 2 },
      { note: 'G4', beats: 1.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'G4', beats: 2 },
      { note: 'D4', beats: 2 }, { note: 'G4', beats: 1.5 }, { note: 'E4', beats: 0.5 },
      { note: 'C4', beats: 4 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '伦敦大桥垮下来\n垮下来 垮下来\n伦敦大桥垮下来\n就在游戏里',
    relatedTopics: ['dotted-rhythm', 'pitch-up-down', 'phrase-question-answer'],
  },
  {
    id: 'abablacksheep',
    title: '咩咩黑羊',
    category: 'nursery',
    level: 1,
    bpm: 100,
    beatsPerBar: 4,
    desc: 'Baa Baa Black Sheep，与小星星同一曲调',
    melody: [
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 2 },
      { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 2 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 2 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 2 },
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 2 },
      { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 2 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'F4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '咩咩 咩咩 黑羊\n你有没有羊毛\n有的 有的 先生\n满满三大袋\n一袋给主人\n一袋给太太\n一袋给巷子里的小娃娃',
    relatedTopics: ['quarter-eighth-notes', 'contrast-repetition', 'c-major-scale'],
  },
  {
    id: 'ifyoure-happy',
    title: '如果感到幸福你就拍拍手',
    category: 'nursery',
    level: 2,
    bpm: 120,
    beatsPerBar: 4,
    desc: 'If You\'re Happy and You Know It，互动律动儿歌',
    melody: [
      { note: 'C4', beats: 0.5 },
      { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'E4', beats: 0.5 }, { note: 'F4', beats: 0.5 },
      { note: 'G4', beats: 2 }, { note: 'rest', beats: 1 }, { note: 'C4', beats: 0.5 }, { note: 'C4', beats: 0.5 },
      { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'E4', beats: 0.5 }, { note: 'F4', beats: 0.5 },
      { note: 'G4', beats: 2 }, { note: 'rest', beats: 1 }, { note: 'C4', beats: 0.5 }, { note: 'C4', beats: 0.5 },
      { note: 'A4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 },
      { note: 'B4', beats: 2 }, { note: 'rest', beats: 1 }, { note: 'C4', beats: 0.5 }, { note: 'C4', beats: 0.5 },
      { note: 'C5', beats: 1 }, { note: 'C5', beats: 1 }, { note: 'C5', beats: 1 }, { note: 'B4', beats: 0.5 }, { note: 'C5', beats: 0.5 },
      { note: 'F4', beats: 2 }, { note: 'rest', beats: 1 }, { note: 'C4', beats: 0.5 }, { note: 'C4', beats: 0.5 },
      { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'E4', beats: 0.5 }, { note: 'F4', beats: 0.5 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'F4', beats: 0.5 }, { note: 'G4', beats: 0.5 },
      { note: 'A4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 },
      { note: 'F4', beats: 2 }, { note: 'rest', beats: 1.5 },
    ],
    chords: [
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '如果感到幸福你就拍拍手\n如果感到幸福你就拍拍手\n如果感到幸福就快快拍拍手呀\n看哪大家一齐拍拍手',
    relatedTopics: ['rests-basic', 'sequence-melodic', 'steady-beat'],
  },
  {
    id: 'do-re-mi',
    title: 'Do-Re-Mi',
    category: 'classic',
    level: 2,
    bpm: 120,
    beatsPerBar: 4,
    desc: '电影《音乐之声》选曲，用音阶学唱名',
    melody: [
      { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'E4', beats: 2 },
      { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'F4', beats: 2 },
      { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'G4', beats: 2 },
      { note: 'F4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'A4', beats: 2 },
      { note: 'G4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'B4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'B4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'B4', beats: 2 },
      { note: 'A4', beats: 1 }, { note: 'B4', beats: 1 }, { note: 'C5', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'B4', beats: 1 }, { note: 'C5', beats: 1 }, { note: 'C5', beats: 2 },
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'B4', beats: 1 }, { note: 'C5', beats: 2 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'F4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'F4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'F4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' },
    ],
    relatedTopics: ['c-major-scale', 'solfege-numbers', 'sequence-melodic'],
  },
  {
    id: 'aura-lee',
    title: '奥拉李',
    category: 'classic',
    level: 3,
    bpm: 90,
    beatsPerBar: 4,
    desc: 'Aura Lee，1861 年美国歌曲（《Love Me Tender》曲调原型）',
    melody: [
      { note: 'rest', beats: 1 },
      { note: 'C4', beats: 1 },
      { note: 'F4', beats: 1.5 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'B4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'A4', beats: 1.5 }, { note: 'B4', beats: 0.5 }, { note: 'C5', beats: 2 },
      { note: 'C5', beats: 1 }, { note: 'B4', beats: 1 },
      { note: 'A4', beats: 1.5 }, { note: 'B4', beats: 0.5 }, { note: 'C5', beats: 1 }, { note: 'B4', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 4 },
    ],
    chords: [
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' },
    ],
    relatedTopics: ['dotted-rhythm', 'melody-contour', 'phrase-question-answer'],
  },
  {
    id: 'surprise',
    title: '惊愕交响曲',
    category: 'classic',
    level: 3,
    bpm: 100,
    beatsPerBar: 4,
    desc: '海顿第 94 号交响曲主题，轻柔之后突然一记强奏',
    melody: [
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 2 },
      { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'B4', beats: 1 }, { note: 'B4', beats: 1 }, { note: 'C5', beats: 2 },
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 2 },
      { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 4 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' },
    ],
    relatedTopics: ['dynamics-basic', 'contrast-repetition', 'motif'],
  },
  {
    id: 'moon-river',
    title: '茉莉花开（民乐）',
    category: 'folk',
    level: 3,
    bpm: 75,
    beatsPerBar: 4,
    desc: '五声风格民乐小曲，宫调式',
    melody: [
      { note: 'C4', beats: 1 }, { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'G4', beats: 1.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'D4', beats: 1 }, { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'E4', beats: 1.5 }, { note: 'D4', beats: 0.5 }, { note: 'C4', beats: 2 },
      { note: 'A4', beats: 1 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'C5', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'G4', beats: 1.5 }, { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 2 },
      { note: 'E4', beats: 1 }, { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 1.5 }, { note: 'C4', beats: 0.5 }, { note: 'C4', beats: 2 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'A3', quality: 'min' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '茉莉花开满庭芳\n清风一吹十里香\n五声音阶轻轻唱\n宫商角徵羽悠扬',
    relatedTopics: ['pentatonic-scale', 'gong-shang-jue-zhi-yu', 'melody-contour'],
  },
  {
    id: 'colorful-clouds',
    title: '彩云追月',
    category: 'folk',
    level: 4,
    bpm: 80,
    beatsPerBar: 4,
    desc: '任光 1935 年创作的广东音乐风格名曲',
    melody: [
      { note: 'G4', beats: 1.5 }, { note: 'A4', beats: 0.5 }, { note: 'C5', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'G4', beats: 1.5 }, { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'G4', beats: 1.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'C4', beats: 2 }, { note: 'rest', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'A4', beats: 1.5 }, { note: 'C5', beats: 0.5 }, { note: 'D5', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'A4', beats: 1.5 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'A4', beats: 1.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'A4', beats: 2 }, { note: 'rest', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'D5', beats: 1.5 }, { note: 'C5', beats: 0.5 }, { note: 'A4', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'G4', beats: 1.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 1.5 }, { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'C4', beats: 3 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'A3', quality: 'min' },
      { root: 'F4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'A3', quality: 'min' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    relatedTopics: ['dotted-rhythm', 'pentatonic-scale', 'syncopation'],
  },
  {
    id: 'edelweiss',
    title: '雪绒花',
    category: 'festival',
    level: 3,
    bpm: 90,
    beatsPerBar: 3,
    desc: 'Edelweiss，电影《音乐之声》插曲，3/4 拍抒情曲',
    melody: [
      { note: 'C4', beats: 1 }, { note: 'G4', beats: 2 },
      { note: 'F4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'F4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'E4', beats: 2 },
      { note: 'C4', beats: 1 }, { note: 'G4', beats: 2 },
      { note: 'F4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'F4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'C5', beats: 2 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'A3', quality: 'min' }, { root: 'F4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'A3', quality: 'min' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    relatedTopics: ['meter-basic', 'melody-contour', 'articulation-basic'],
  },
  {
    id: 'we-wish',
    title: '祝你圣诞快乐',
    category: 'festival',
    level: 2,
    bpm: 120,
    beatsPerBar: 3,
    desc: 'We Wish You a Merry Christmas，英国圣诞颂歌',
    melody: [
      { note: 'rest', beats: 2 },
      { note: 'C4', beats: 1 },
      { note: 'F4', beats: 1 }, { note: 'F4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'F4', beats: 0.5 }, { note: 'E4', beats: 0.5 },
      { note: 'D4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'F4', beats: 0.5 },
      { note: 'E4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'A4', beats: 0.5 }, { note: 'B4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 },
      { note: 'F4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 0.5 }, { note: 'C4', beats: 0.5 },
      { note: 'D4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'F4', beats: 2 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'F4', quality: 'maj' }, { root: 'F4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'A3', quality: 'min' },
      { root: 'D4', quality: 'min' }, { root: 'G4', quality: 'maj' },
      { root: 'F4', quality: 'maj' },
    ],
    lyrics: '祝你圣诞快乐\n祝你圣诞快乐\n祝你圣诞快乐\n新年多快乐',
    relatedTopics: ['offbeat', 'quarter-eighth-notes', 'meter-basic'],
  },
  {
    id: 'auld-lang',
    title: '友谊地久天长',
    category: 'festival',
    level: 3,
    bpm: 90,
    beatsPerBar: 4,
    desc: 'Auld Lang Syne，苏格兰民歌，新年惜别曲',
    melody: [
      { note: 'rest', beats: 3 },
      { note: 'C4', beats: 1 },
      { note: 'F4', beats: 1.5 }, { note: 'F4', beats: 0.5 }, { note: 'F4', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'C5', beats: 3 }, { note: 'C5', beats: 1 },
      { note: 'C5', beats: 1.5 }, { note: 'C5', beats: 0.5 }, { note: 'C5', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'F4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 3 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'F4', quality: 'maj' }, { root: 'F4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'F4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'F4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'F4', quality: 'maj' },
    ],
    lyrics: '怎能忘记旧日朋友\n心中能不怀想\n旧日朋友岂能相忘\n友谊地久天长',
    relatedTopics: ['dotted-rhythm', 'offbeat', 'melody-contour'],
  },
  {
    id: 'little-bee',
    title: '小蜜蜂',
    category: 'nursery',
    level: 1,
    bpm: 110,
    beatsPerBar: 2,
    desc: '嗡嗡嗡，采蜜忙，二拍子律动',
    melody: [
      { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'D4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'D4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'C4', beats: 2 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '嗡嗡嗡 嗡嗡嗡\n大家一起勤做工\n来匆匆 去匆匆\n做工兴味浓',
    relatedTopics: ['steady-beat', 'meter-basic', 'pitch-up-down'],
  },
  {
    id: 'counting-ducks',
    title: '数鸭子',
    category: 'nursery',
    level: 2,
    bpm: 120,
    beatsPerBar: 2,
    desc: '门前大桥下，游过一群鸭',
    melody: [
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'C4', beats: 0.5 }, { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 0.5 }, { note: 'C4', beats: 1 },
      { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'C4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 2 },
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'C4', beats: 0.5 }, { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 0.5 }, { note: 'C4', beats: 1 },
      { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'C4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 2 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'A3', quality: 'min' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'A3', quality: 'min' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '门前大桥下\n游过一群鸭\n快来快来数一数\n二四六七八\n嘎嘎嘎嘎\n真呀真多呀\n数不清到底多少鸭',
    relatedTopics: ['quarter-eighth-notes', 'call-response', 'steady-beat'],
  },
  {
    id: 'grandma-bridge',
    title: '摇到外婆桥',
    category: 'nursery',
    level: 1,
    bpm: 90,
    beatsPerBar: 4,
    desc: '摇啊摇，摇到外婆桥，江南童谣',
    melody: [
      { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 2 },
      { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'C4', beats: 2 },
      { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'A4', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 2 },
      { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'C4', beats: 2 },
    ],
    chords: [
      { root: 'A3', quality: 'min' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '摇啊摇 摇啊摇\n摇到外婆桥\n外婆叫我好宝宝\n糖一包 果一包\n还有饼儿还有糕',
    relatedTopics: ['pentatonic-scale', 'phrase-question-answer', 'steady-beat'],
  },
  {
    id: 'spring-buds',
    title: '春天在哪里',
    category: 'nursery',
    level: 2,
    bpm: 120,
    beatsPerBar: 4,
    desc: '潘振声词曲，春天在那青翠的山林里',
    melody: [
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 0.5 }, { note: 'C4', beats: 0.5 },
      { note: 'D4', beats: 2 }, { note: 'rest', beats: 1 }, { note: 'C4', beats: 0.5 }, { note: 'E4', beats: 0.5 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 0.5 }, { note: 'C4', beats: 0.5 },
      { note: 'C4', beats: 2 }, { note: 'rest', beats: 1 }, { note: 'C4', beats: 0.5 }, { note: 'D4', beats: 0.5 },
      { note: 'E4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 0.5 }, { note: 'C4', beats: 1 },
      { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'A3', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'C4', beats: 4 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'A3', quality: 'min' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '春天在哪里呀\n春天在哪里\n春天在那青翠的山林里\n这里有红花呀\n这里有绿草\n还有那会唱歌的小黄鹂',
    relatedTopics: ['quarter-eighth-notes', 'rests-basic', 'melody-contour'],
  },
  {
    id: 'clementine',
    title: '我的邦妮',
    category: 'classic',
    level: 2,
    bpm: 100,
    beatsPerBar: 3,
    desc: 'My Bonnie Lies over the Ocean，苏格兰民歌，3/4 拍',
    melody: [
      { note: 'rest', beats: 2 },
      { note: 'C4', beats: 1 },
      { note: 'F4', beats: 1.5 }, { note: 'F4', beats: 0.5 }, { note: 'F4', beats: 1 },
      { note: 'A4', beats: 1.5 }, { note: 'G4', beats: 0.5 }, { note: 'F4', beats: 1 },
      { note: 'E4', beats: 1.5 }, { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 1 },
      { note: 'F4', beats: 2 }, { note: 'C4', beats: 1 },
      { note: 'F4', beats: 1.5 }, { note: 'F4', beats: 0.5 }, { note: 'F4', beats: 1 },
      { note: 'A4', beats: 1.5 }, { note: 'G4', beats: 0.5 }, { note: 'F4', beats: 1 },
      { note: 'E4', beats: 1.5 }, { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 1 },
      { note: 'F4', beats: 2 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'F4', quality: 'maj' }, { root: 'F4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'F4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'F4', quality: 'maj' },
    ],
    lyrics: '我的邦妮躺卧在海洋\n我的邦妮躺卧在海洋\n哦 带回来 哦 带回来\n哦 带回来我的邦妮',
    relatedTopics: ['dotted-rhythm', 'meter-basic', 'offbeat'],
  },
  {
    id: 'greensleeves',
    title: '绿袖子',
    category: 'classic',
    level: 4,
    bpm: 90,
    beatsPerBar: 3,
    desc: 'Greensleeves，英国民谣，a 小调的忧伤色彩',
    melody: [
      { note: 'rest', beats: 2 },
      { note: 'A4', beats: 1 },
      { note: 'C5', beats: 1.5 }, { note: 'D5', beats: 0.5 }, { note: 'E5', beats: 1 },
      { note: 'F5', beats: 1.5 }, { note: 'E5', beats: 0.5 }, { note: 'D5', beats: 1 },
      { note: 'B4', beats: 1.5 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 1 },
      { note: 'B4', beats: 1.5 }, { note: 'C5', beats: 0.5 }, { note: 'A4', beats: 1 },
      { note: 'A4', beats: 1.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 1.5 }, { note: 'E4', beats: 0.5 }, { note: 'F4', beats: 1 },
      { note: 'E4', beats: 1.5 }, { note: 'D4', beats: 0.5 }, { note: 'B4', beats: 1 },
      { note: 'A4', beats: 2 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'A4', quality: 'min' }, { root: 'C4', quality: 'maj' },
      { root: 'D4', quality: 'min' }, { root: 'G4', quality: 'maj' },
      { root: 'A4', quality: 'min' }, { root: 'A4', quality: 'min' },
      { root: 'D4', quality: 'min' }, { root: 'E4', quality: 'min' },
      { root: 'A4', quality: 'min' },
    ],
    relatedTopics: ['major-minor-feeling', 'dotted-rhythm', 'melody-contour'],
  },
  {
    id: 'swan-lake',
    title: '天鹅湖主题',
    category: 'classic',
    level: 4,
    bpm: 90,
    beatsPerBar: 4,
    desc: '柴可夫斯基芭蕾舞剧《天鹅湖》场景主题，e 小调',
    melody: [
      { note: 'B4', beats: 2 },
      { note: 'E5', beats: 1.5 }, { note: 'F5', beats: 0.5 }, { note: 'G5', beats: 1 }, { note: 'F5', beats: 1 },
      { note: 'E5', beats: 1 }, { note: 'B5', beats: 1 }, { note: 'A5', beats: 2 },
      { note: 'A5', beats: 1.5 }, { note: 'F5', beats: 0.5 }, { note: 'E5', beats: 1 }, { note: 'F5', beats: 1 },
      { note: 'E5', beats: 1 }, { note: 'D5', beats: 1 }, { note: 'C5', beats: 2 },
      { note: 'C5', beats: 1.5 }, { note: 'A4', beats: 0.5 }, { note: 'B4', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'D5', beats: 1 }, { note: 'E5', beats: 1 }, { note: 'F5', beats: 2 },
      { note: 'F5', beats: 1.5 }, { note: 'D5', beats: 0.5 }, { note: 'C5', beats: 1 }, { note: 'B4', beats: 1 },
      { note: 'A4', beats: 1 }, { note: 'B4', beats: 1 }, { note: 'E5', beats: 2 },
      { note: 'E5', beats: 1.5 }, { note: 'C5', beats: 0.5 }, { note: 'B4', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'G4', beats: 1 }, { note: 'F4', beats: 1 }, { note: 'B4', beats: 3 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'E4', quality: 'min' }, { root: 'C4', quality: 'maj' },
      { root: 'A3', quality: 'min' }, { root: 'B4', quality: 'min' },
      { root: 'A3', quality: 'min' }, { root: 'D4', quality: 'min' },
      { root: 'C4', quality: 'maj' }, { root: 'A3', quality: 'min' },
      { root: 'C4', quality: 'maj' }, { root: 'B4', quality: 'min' },
      { root: 'E4', quality: 'min' },
    ],
    relatedTopics: ['major-minor-feeling', 'dotted-rhythm', 'orchestra-sections'],
  },
  {
    id: 'song-of-joy',
    title: '送别',
    category: 'folk',
    level: 3,
    bpm: 75,
    beatsPerBar: 4,
    desc: '李叔同填词，长亭外，古道边',
    melody: [
      { note: 'rest', beats: 3 },
      { note: 'G4', beats: 1 },
      { note: 'C5', beats: 1.5 }, { note: 'C5', beats: 0.5 }, { note: 'B4', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'E5', beats: 1.5 }, { note: 'D5', beats: 0.5 }, { note: 'C5', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'G4', beats: 2 }, { note: 'rest', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'A4', beats: 1.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'C5', beats: 1.5 }, { note: 'B4', beats: 0.5 }, { note: 'A4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'E4', beats: 2 }, { note: 'rest', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'A4', beats: 1.5 }, { note: 'C5', beats: 0.5 }, { note: 'B4', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'E5', beats: 1.5 }, { note: 'D5', beats: 0.5 }, { note: 'C5', beats: 1 }, { note: 'A4', beats: 1 },
      { note: 'G4', beats: 2 }, { note: 'rest', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'F4', beats: 1.5 }, { note: 'F4', beats: 0.5 }, { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'D4', beats: 1.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 1 },
      { note: 'C4', beats: 3 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'A3', quality: 'min' }, { root: 'G4', quality: 'maj' },
      { root: 'A3', quality: 'min' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'A3', quality: 'min' },
      { root: 'F4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'F4', quality: 'maj' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' },
    ],
    lyrics: '长亭外 古道边\n芳草碧连天\n晚风拂柳笛声残\n夕阳山外山\n天之涯 地之角\n知交半零落\n一壶浊酒尽余欢\n今宵别梦寒',
    relatedTopics: ['dotted-rhythm', 'offbeat', 'melody-ending'],
  },
  {
    id: 'in-that-place',
    title: '在那遥远的地方',
    category: 'folk',
    level: 3,
    bpm: 80,
    beatsPerBar: 4,
    desc: '王洛宾词曲，西部民歌代表作',
    melody: [
      { note: 'G4', beats: 1.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'G4', beats: 1.5 }, { note: 'A4', beats: 0.5 }, { note: 'C5', beats: 2 },
      { note: 'A4', beats: 1.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 3 }, { note: 'rest', beats: 1 },
      { note: 'G4', beats: 1.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'G4', beats: 1.5 }, { note: 'A4', beats: 0.5 }, { note: 'C5', beats: 2 },
      { note: 'A4', beats: 1.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 3 }, { note: 'rest', beats: 1 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'G4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '在那遥远的地方\n有位好姑娘\n人们走过了她的帐房\n都要回头留恋地张望',
    relatedTopics: ['dotted-rhythm', 'pentatonic-scale', 'folk-song-region'],
  },
  {
    id: 'colorful-yunnan',
    title: '小放牛',
    category: 'folk',
    level: 2,
    bpm: 100,
    beatsPerBar: 2,
    desc: '河北民歌，一问一答的对唱小调',
    melody: [
      { note: 'C4', beats: 0.5 }, { note: 'D4', beats: 0.5 },
      { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 },
      { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'C5', beats: 1 },
      { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 },
      { note: 'D4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 1 },
      { note: 'C4', beats: 2 },
      { note: 'E4', beats: 0.5 }, { note: 'G4', beats: 0.5 },
      { note: 'A4', beats: 1 }, { note: 'C5', beats: 1 },
      { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 },
      { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 1 },
      { note: 'E4', beats: 0.5 }, { note: 'D4', beats: 0.5 }, { note: 'C4', beats: 1 },
      { note: 'C4', beats: 2 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'A3', quality: 'min' }, { root: 'C4', quality: 'maj' },
      { root: 'A3', quality: 'min' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'A3', quality: 'min' },
      { root: 'A3', quality: 'min' }, { root: 'G4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '赵州桥来什么人修\n玉石栏杆什么人留\n什么人骑驴桥上走\n什么人推车压了一趟沟',
    relatedTopics: ['quarter-eighth-notes', 'call-response', 'pentatonic-scale'],
  },
  {
    id: 'happy-newyear',
    title: '新年好',
    category: 'festival',
    level: 1,
    bpm: 110,
    beatsPerBar: 4,
    desc: '新年好呀，新年好呀，贺年歌',
    melody: [
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'C4', beats: 0.5 }, { note: 'G3', beats: 0.5 },
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 0.5 }, { note: 'C4', beats: 0.5 },
      { note: 'C4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'F4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'B3', beats: 1 },
      { note: 'C4', beats: 1 }, { note: 'C4', beats: 1 }, { note: 'C4', beats: 0.5 }, { note: 'G3', beats: 0.5 },
      { note: 'E4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'E4', beats: 0.5 }, { note: 'C4', beats: 0.5 },
      { note: 'C4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'F4', beats: 1 }, { note: 'E4', beats: 1 }, { note: 'D4', beats: 1 }, { note: 'C4', beats: 1 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'G3', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' },
    ],
    lyrics: '新年好呀 新年好呀\n祝贺大家新年好\n我们唱歌 我们跳舞\n祝贺大家新年好',
    relatedTopics: ['quarter-eighth-notes', 'steady-beat', 'repeat-signs'],
  },
  {
    id: 'lantern',
    title: '卖汤圆',
    category: 'festival',
    level: 2,
    bpm: 120,
    beatsPerBar: 4,
    desc: '台湾民谣，卖汤圆，卖汤圆，小二哥的汤圆是圆又圆',
    melody: [
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'G4', beats: 1.5 }, { note: 'A4', beats: 0.5 }, { note: 'C5', beats: 2 },
      { note: 'C5', beats: 1 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'E4', beats: 1.5 }, { note: 'D4', beats: 0.5 }, { note: 'C4', beats: 2 },
      { note: 'G4', beats: 1 }, { note: 'G4', beats: 0.5 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 1 }, { note: 'E4', beats: 1 },
      { note: 'G4', beats: 1.5 }, { note: 'A4', beats: 0.5 }, { note: 'C5', beats: 2 },
      { note: 'C5', beats: 1 }, { note: 'A4', beats: 0.5 }, { note: 'G4', beats: 0.5 }, { note: 'E4', beats: 1 }, { note: 'G4', beats: 1 },
      { note: 'D4', beats: 1.5 }, { note: 'E4', beats: 0.5 }, { note: 'C4', beats: 2 },
    ],
    chords: [
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'A3', quality: 'min' }, { root: 'C4', quality: 'maj' },
      { root: 'C4', quality: 'maj' }, { root: 'C4', quality: 'maj' },
      { root: 'A3', quality: 'min' }, { root: 'C4', quality: 'maj' },
    ],
    lyrics: '卖汤圆 卖汤圆\n小二哥的汤圆是圆又圆\n一碗汤圆满又满\n三毛钱呀买一碗\n汤圆汤圆卖汤圆\n汤圆一样可以当茶饭',
    relatedTopics: ['dotted-rhythm', 'quarter-eighth-notes', 'pentatonic-scale'],
  },
]
