import type { DemoKind, TheoryStageId, TheoryTopic } from './theoryCatalog'

type TopicDraft = Omit<TheoryTopic, 'actions' | 'demo'> & {
  demo: DemoKind
}

const actionMap: Record<string, TheoryTopic['actions']> = {
  '音高与唱名': [
    { label: '钢琴示范', route: 'piano' },
    { label: '听觉辨识训练', route: 'game-ear' },
  ],
  '节奏与节拍': [
    { label: '节奏反应训练', route: 'game-taiko' },
    { label: '混音器创编', route: 'mixer' },
  ],
  '记谱与读谱': [
    { label: '读谱训练', route: 'game-read' },
    { label: '曲库谱例', route: 'library' },
  ],
  '调式与音阶': [
    { label: '钢琴示范', route: 'piano' },
    { label: '音准与视唱训练', route: 'game-sing' },
  ],
  '音程与和声': [
    { label: '听觉辨识训练', route: 'game-ear' },
    { label: '钢琴示范', route: 'piano' },
  ],
  '速度力度与表情': [
    { label: '音准与视唱训练', route: 'game-sing' },
    { label: '曲库谱例', route: 'library' },
  ],
  '曲式结构': [
    { label: '曲库谱例', route: 'library' },
    { label: '混音器创编', route: 'mixer' },
  ],
  '创作与编配': [
    { label: '混音器创编', route: 'mixer' },
    { label: '钢琴示范', route: 'piano' },
  ],
  '民族与课堂常识': [
    { label: '曲库谱例', route: 'library' },
    { label: '竖笛指法', route: 'recorder' },
  ],
}

function makeTopic(draft: TopicDraft): TheoryTopic {
  return {
    ...draft,
    actions: actionMap[draft.category] ?? actionMap['音高与唱名'],
    demo: {
      kind: draft.demo,
      title: `${draft.title}互动实验`,
      caption: `通过听、看、点选来理解“${draft.subtitle}”。`,
    },
  }
}

const q = (topic: string, right: string, wrongA: string, wrongB: string) => ({
  q: `${topic}最应该关注什么？`,
  options: [right, wrongA, wrongB],
  answer: 0,
})

const extraQuizFor = (topic: TheoryTopic) => [
  {
    q: `学习“${topic.title}”时，最适合先做什么？`,
    options: ['先听或观察例子', '直接背答案', '跳过节拍'],
    answer: 0,
  },
  {
    q: `“${topic.title}”属于哪个教学类别？`,
    options: [topic.category, '课堂座位', '文件保存'],
    answer: 0,
  },
]

export function enrichTheoryTopicQuiz(topic: TheoryTopic): TheoryTopic {
  if (topic.quiz.length >= 4) return topic
  return {
    ...topic,
    quiz: [...topic.quiz, ...extraQuizFor(topic)].slice(0, 4),
  }
}

const drafts: TopicDraft[] = [
  {
    id: 'voice-register',
    category: '音高与唱名',
    stage: 'primary-middle',
    level: 'L2',
    title: '音区',
    subtitle: '高音区、中音区、低音区',
    concept: '音区描述声音所在的高低范围，帮助学生理解不同乐器和人声的位置。',
    keyPoints: ['低音区厚实', '中音区自然', '高音区明亮'],
    demo: 'pitch',
    quiz: [q('音区', '声音所在范围', '速度快慢', '力度大小'), { q: '高音区通常听起来？', options: ['更明亮', '更低沉', '没有音高'], answer: 0 }],
  },
  {
    id: 'melodic-step-leap',
    category: '音高与唱名',
    stage: 'primary-upper',
    level: 'L3',
    title: '级进与跳进',
    subtitle: '相邻移动与跨越移动',
    concept: '级进让旋律平稳，跳进让旋律更有起伏和记忆点。',
    keyPoints: ['级进相邻移动', '跳进跨过音级', '二者组合形成旋律性格'],
    demo: 'pitch',
    quiz: [q('级进与跳进', '旋律移动方式', '音量大小', '曲名长短'), { q: '相邻音级移动叫？', options: ['级进', '跳进', '转位'], answer: 0 }],
  },
  {
    id: 'sequence-melodic',
    category: '音高与唱名',
    stage: 'junior-basic',
    level: 'L4',
    title: '模进',
    subtitle: '同一动机换高度重复',
    concept: '模进是把同一旋律材料移到新的高度重复，是发展旋律的重要方法。',
    keyPoints: ['材料相似', '高度改变', '推动音乐发展'],
    demo: 'scale',
    quiz: [q('模进', '同一材料换高度', '完全停止', '只改音色'), { q: '模进常用来？', options: ['发展旋律', '删除节拍', '取消谱号'], answer: 0 }],
  },
  {
    id: 'chromatic-neighbor',
    category: '音高与唱名',
    stage: 'junior-basic',
    level: 'L4',
    title: '半音邻音',
    subtitle: '靠近主音的装饰移动',
    concept: '半音邻音用很近的音高装饰旋律，常带来细腻或紧张的色彩。',
    keyPoints: ['距离很近', '常作装饰', '可制造张力'],
    demo: 'interval',
    quiz: [q('半音邻音', '近距离装饰', '整段重复', '速度术语'), { q: '半音邻音常带来？', options: ['细腻张力', '完全静止', '无节拍'], answer: 0 }],
  },
  {
    id: 'vocal-range',
    category: '音高与唱名',
    stage: 'junior-advanced',
    level: 'L5',
    title: '音域',
    subtitle: '能唱或能奏的范围',
    concept: '音域是一个人声或乐器能自然表现的音高范围，选曲和移调都要考虑音域。',
    keyPoints: ['音域有高低边界', '选曲要合适', '移调可调整音域'],
    demo: 'pitch',
    quiz: [q('音域', '可唱可奏范围', '小节数量', '音符颜色'), { q: '歌曲太高时可以考虑？', options: ['移调', '删除拍号', '只唱歌词'], answer: 0 }],
  },
  {
    id: 'intonation-center',
    category: '音高与唱名',
    stage: 'junior-advanced',
    level: 'L5',
    title: '音准中心',
    subtitle: '围绕稳定音调整',
    concept: '音准中心帮助演唱者围绕调性稳定音调整高低，减少跑调。',
    keyPoints: ['稳定音作参照', '听唱要结合', '偏高偏低要修正'],
    demo: 'pitch',
    quiz: [q('音准中心', '稳定音参照', '歌词字体', '节拍颜色'), { q: '修正音准要注意？', options: ['偏高偏低', '按钮形状', '页面宽度'], answer: 0 }],
  },

  {
    id: 'sixteenth-notes',
    category: '节奏与节拍',
    stage: 'primary-middle',
    level: 'L2',
    title: '十六分音符',
    subtitle: '更密的拍内细分',
    concept: '十六分音符把一拍分得更细，常让节奏更活泼。',
    keyPoints: ['四个十六分常等于一拍', '拍内要均匀', '速度快时更要慢练'],
    demo: 'duration',
    quiz: [q('十六分音符', '拍内细分', '谱号种类', '和弦色彩'), { q: '四个十六分音符常等于？', options: ['一拍', '四拍', '八拍'], answer: 0 }],
  },
  {
    id: 'rhythm-pattern-ta-ta-ti',
    category: '节奏与节拍',
    stage: 'primary-lower',
    level: 'L1',
    title: '节奏口令',
    subtitle: 'ta、ti-ti、休',
    concept: '用口令读节奏能帮助低龄学生把抽象时值变成身体语言。',
    keyPoints: ['ta 表示一拍', 'ti-ti 表示两个半拍', '休要心里数'],
    demo: 'duration',
    quiz: [q('节奏口令', '把节奏说出来', '背曲名', '改音色'), { q: 'ti-ti 通常表示？', options: ['两个半拍', '四拍长音', '完全停止'], answer: 0 }],
  },
  {
    id: 'offbeat',
    category: '节奏与节拍',
    stage: 'primary-upper',
    level: 'L3',
    title: '弱起与反拍',
    subtitle: '不从强拍开始',
    concept: '弱起和反拍让音乐更有弹性，常见于歌曲、舞曲和流行节奏。',
    keyPoints: ['弱起在强拍前进入', '反拍强调弱位置', '律动更轻快'],
    demo: 'meter',
    quiz: [q('弱起与反拍', '进入和重音位置', '谱号形状', '音名拼写'), { q: '弱起通常发生在？', options: ['强拍前', '曲终后', '没有节拍处'], answer: 0 }],
  },
  {
    id: 'hemiola',
    category: '节奏与节拍',
    stage: 'junior-basic',
    level: 'L4',
    title: '交错重音',
    subtitle: '二拍感与三拍感转换',
    concept: '交错重音会让听感在二拍和三拍之间转换，是节奏张力的重要来源。',
    keyPoints: ['重音重新组合', '听感会转换', '常用于舞曲和合唱'],
    demo: 'meter',
    quiz: [q('交错重音', '重音组合变化', '调号数量', '歌词声母'), { q: '交错重音会改变？', options: ['节拍听感', '乐器材质', '谱纸大小'], answer: 0 }],
  },
  {
    id: 'polyrhythm-intro',
    category: '节奏与节拍',
    stage: 'junior-advanced',
    level: 'L5',
    title: '复合节奏入门',
    subtitle: '两种节奏层同时出现',
    concept: '复合节奏让不同声部同时呈现不同节奏层，形成丰富的律动。',
    keyPoints: ['多个节奏层', '共同脉搏很重要', '先分层再合成'],
    demo: 'meter',
    quiz: [q('复合节奏', '多个节奏层', '只有一个长音', '删除小节'), { q: '练复合节奏要先？', options: ['分层练习', '直接加速', '忽略强拍'], answer: 0 }],
  },
  {
    id: 'rhythmic-motif',
    category: '节奏与节拍',
    stage: 'junior-basic',
    level: 'L4',
    title: '节奏动机',
    subtitle: '可记住的节奏种子',
    concept: '节奏动机是短小、有辨识度的节奏材料，可以推动整首作品。',
    keyPoints: ['短小清楚', '可重复变化', '支撑音乐性格'],
    demo: 'repeat',
    quiz: [q('节奏动机', '短小节奏材料', '低音谱号', '调式中心'), { q: '节奏动机可以怎样发展？', options: ['重复变化', '完全丢掉', '只改标题'], answer: 0 }],
  },

  {
    id: 'grand-staff',
    category: '记谱与读谱',
    stage: 'primary-upper',
    level: 'L3',
    title: '钢琴大谱表',
    subtitle: '高音谱表与低音谱表',
    concept: '钢琴大谱表把高音谱号和低音谱号连在一起，常用于同时记录左右手。',
    keyPoints: ['上方多为高音谱表', '下方多为低音谱表', '中央 C 是连接点'],
    demo: 'staff',
    quiz: [q('钢琴大谱表', '高低谱表结合', '速度变化', '打击方式'), { q: '钢琴大谱表常用于？', options: ['左右手记谱', '只记歌词', '只记速度'], answer: 0 }],
  },
  {
    id: 'repeat-endings',
    category: '记谱与读谱',
    stage: 'junior-basic',
    level: 'L4',
    title: '一房子二房子',
    subtitle: '不同结尾的反复',
    concept: '一房子二房子表示第一次和第二次反复时走不同结尾。',
    keyPoints: ['第一次进一房子', '第二次跳到二房子', '要看清反复路线'],
    demo: 'repeat',
    quiz: [q('一房子二房子', '不同结尾路线', '音区变化', '和弦根音'), { q: '第二遍通常进入？', options: ['二房子', '一房子', '谱号'], answer: 0 }],
  },
  {
    id: 'dc-ds-coda',
    category: '记谱与读谱',
    stage: 'junior-advanced',
    level: 'L5',
    title: 'D.C.、D.S. 与 Coda',
    subtitle: '复杂反复路线',
    concept: 'D.C.、D.S. 和 Coda 是常见的反复与跳转标记，用来组织较长乐曲。',
    keyPoints: ['D.C. 回到开头', 'D.S. 回到记号处', 'Coda 指向尾声'],
    demo: 'repeat',
    quiz: [q('D.C. D.S. Coda', '乐曲跳转路线', '力度等级', '音名顺序'), { q: 'D.C. 常表示？', options: ['回到开头', '降低半音', '渐强'], answer: 0 }],
  },
  {
    id: 'beaming-groups',
    category: '记谱与读谱',
    stage: 'primary-upper',
    level: 'L3',
    title: '符尾连线分组',
    subtitle: '看清拍内组合',
    concept: '八分、十六分音符常用符尾连接，分组能帮助读出拍内结构。',
    keyPoints: ['符尾连接短音', '按拍分组更清楚', '分组服务读谱'],
    demo: 'duration',
    quiz: [q('符尾连线分组', '拍内结构', '和弦明暗', '音区高低'), { q: '符尾分组有助于？', options: ['读节奏', '改变音色', '删除调号'], answer: 0 }],
  },
  {
    id: 'score-markings-order',
    category: '记谱与读谱',
    stage: 'junior-basic',
    level: 'L4',
    title: '谱面标记优先级',
    subtitle: '先看整体再看细节',
    concept: '拿到新谱时先看谱号、调号、拍号、速度，再看音符、表情和结构。',
    keyPoints: ['先读头部信息', '再读音高节奏', '最后处理表情结构'],
    demo: 'staff',
    quiz: [q('谱面标记优先级', '读谱顺序', '按钮颜色', '座位安排'), { q: '新谱第一眼适合看？', options: ['谱号调号拍号', '最后一小节', '文件名'], answer: 0 }],
  },
  {
    id: 'clef-change',
    category: '记谱与读谱',
    stage: 'junior-advanced',
    level: 'L5',
    title: '临时换谱号',
    subtitle: '为避免过多加线',
    concept: '乐曲中可能临时换谱号，让过高或过低的音更容易阅读。',
    keyPoints: ['换谱号改变读法', '减少加线', '常见于宽音域乐器'],
    demo: 'staff',
    quiz: [q('临时换谱号', '改变读谱参照', '改变速度', '改变拍号'), { q: '换谱号常为了？', options: ['减少加线', '增加歌词', '取消音高'], answer: 0 }],
  },

  {
    id: 'g-major-scale',
    category: '调式与音阶',
    stage: 'primary-upper',
    level: 'L3',
    title: 'G 大调音阶',
    subtitle: '一个升号的大调',
    concept: 'G 大调以 G 为主音，调号有一个升号 F#。',
    keyPoints: ['主音是 G', '有 F#', '常见于明亮歌曲'],
    demo: 'scale',
    quiz: [q('G 大调', '主音和 F#', '休止符形状', '速度术语'), { q: 'G 大调的主音是？', options: ['G', 'C', 'F'], answer: 0 }],
  },
  {
    id: 'f-major-scale',
    category: '调式与音阶',
    stage: 'primary-upper',
    level: 'L3',
    title: 'F 大调音阶',
    subtitle: '一个降号的大调',
    concept: 'F 大调以 F 为主音，调号有一个降号 Bb。',
    keyPoints: ['主音是 F', '有 Bb', '色彩温暖'],
    demo: 'scale',
    quiz: [q('F 大调', '主音和 Bb', '节奏口令', '连音奏法'), { q: 'F 大调常有哪个降音？', options: ['Bb', 'F#', 'C#'], answer: 0 }],
  },
  {
    id: 'harmonic-minor',
    category: '调式与音阶',
    stage: 'junior-basic',
    level: 'L4',
    title: '和声小调',
    subtitle: '升高第七级',
    concept: '和声小调常升高第七级，增强导向主音的倾向。',
    keyPoints: ['第七级升高', '导向感增强', '常用于和声终止'],
    demo: 'scale',
    quiz: [q('和声小调', '升高第七级', '删除强拍', '只用五个音'), { q: '和声小调常升高？', options: ['第七级', '第一拍', '谱号'], answer: 0 }],
  },
  {
    id: 'melodic-minor',
    category: '调式与音阶',
    stage: 'junior-advanced',
    level: 'L5',
    title: '旋律小调',
    subtitle: '上行和下行变化',
    concept: '旋律小调常在上行时调整第六、第七级，让旋律更顺畅。',
    keyPoints: ['上行更平滑', '六七级常变化', '服务旋律进行'],
    demo: 'scale',
    quiz: [q('旋律小调', '旋律顺畅', '节奏强弱', '乐器分类'), { q: '旋律小调变化常服务于？', options: ['旋律进行', '谱面颜色', '文件保存'], answer: 0 }],
  },
  {
    id: 'gong-shang-jue-zhi-yu',
    category: '调式与音阶',
    stage: 'junior-basic',
    level: 'L4',
    title: '宫商角徵羽',
    subtitle: '中国五声调式名称',
    concept: '宫、商、角、徵、羽是中国传统五声体系的重要名称。',
    keyPoints: ['对应五声骨干音', '体现民族调式', '常用于民歌分析'],
    demo: 'scale',
    quiz: [q('宫商角徵羽', '五声调式名称', '西洋速度词', '鼓点口令'), { q: '宫商角徵羽属于？', options: ['中国五声体系', '力度记号', '谱号'], answer: 0 }],
  },
  {
    id: 'modulation-pivot',
    category: '调式与音阶',
    stage: 'junior-advanced',
    level: 'L5',
    title: '共同音转调',
    subtitle: '用共享音连接调性',
    concept: '共同音转调通过两个调都拥有的音或和弦，让调性变化更自然。',
    keyPoints: ['共享材料连接', '调性变化更平滑', '常用于较长作品'],
    demo: 'chord',
    quiz: [q('共同音转调', '共享音或和弦', '删除旋律', '改变歌词字体'), { q: '共同音转调追求？', options: ['平滑转换', '完全中断', '只剩节奏'], answer: 0 }],
  },

  {
    id: 'primary-triads',
    category: '音程与和声',
    stage: 'junior-basic',
    level: 'L4',
    title: '正三和弦',
    subtitle: 'I、IV、V',
    concept: '正三和弦是调内最核心的和弦，常支撑歌曲的基本和声。',
    keyPoints: ['I 是主和弦', 'IV 是下属和弦', 'V 是属和弦'],
    demo: 'chord',
    quiz: [q('正三和弦', 'I IV V 功能', '歌词段落', '音色分类'), { q: 'V 级和弦常叫？', options: ['属和弦', '主和弦', '休止符'], answer: 0 }],
  },
  {
    id: 'harmonic-function',
    category: '音程与和声',
    stage: 'junior-advanced',
    level: 'L5',
    title: '和声功能',
    subtitle: '稳定、离开、回归',
    concept: '和声功能描述和弦在调性中的作用，如主功能、下属功能和属功能。',
    keyPoints: ['主功能稳定', '下属功能离开', '属功能导向回归'],
    demo: 'chord',
    quiz: [q('和声功能', '和弦作用', '音符写法', '速度单位'), { q: '主功能通常给人？', options: ['稳定感', '完全无声', '拍号变化'], answer: 0 }],
  },
  {
    id: 'broken-chord',
    category: '音程与和声',
    stage: 'primary-upper',
    level: 'L3',
    title: '分解和弦',
    subtitle: '和弦音依次弹出',
    concept: '分解和弦把和弦音依次弹出，常用于伴奏和旋律装饰。',
    keyPoints: ['来自和弦', '依次发声', '伴奏常用'],
    demo: 'chord',
    quiz: [q('分解和弦', '和弦音依次出现', '所有音同时休止', '改变调号'), { q: '分解和弦常用于？', options: ['伴奏', '删除旋律', '标记速度'], answer: 0 }],
  },
  {
    id: 'suspension',
    category: '音程与和声',
    stage: 'junior-advanced',
    level: 'L5',
    title: '挂留音',
    subtitle: '延迟解决的张力',
    concept: '挂留音把前一个和声中的音保留到新和声中，形成短暂张力后解决。',
    keyPoints: ['保留旧音', '产生张力', '随后解决'],
    demo: 'chord',
    quiz: [q('挂留音', '延迟解决张力', '速度加快', '拍号减少'), { q: '挂留音最后通常需要？', options: ['解决', '消失页面', '变成谱号'], answer: 0 }],
  },
  {
    id: 'bass-line',
    category: '音程与和声',
    stage: 'junior-basic',
    level: 'L4',
    title: '低音线',
    subtitle: '和声的地基',
    concept: '低音线支撑和声根基，也能形成独立的旋律走向。',
    keyPoints: ['支撑和声', '影响稳定感', '可形成走向'],
    demo: 'chord',
    quiz: [q('低音线', '和声根基', '歌词押韵', '谱纸大小'), { q: '低音线会影响？', options: ['和声稳定感', '题库数量', '按钮颜色'], answer: 0 }],
  },
  {
    id: 'parallel-motion',
    category: '音程与和声',
    stage: 'junior-advanced',
    level: 'L5',
    title: '平行进行',
    subtitle: '两个声部同向移动',
    concept: '平行进行是多个声部保持相似距离同向移动，会形成统一的色彩。',
    keyPoints: ['声部同向', '距离相似', '色彩统一'],
    demo: 'interval',
    quiz: [q('平行进行', '声部同向移动', '拍号上方数字', '力度缩写'), { q: '平行进行常带来？', options: ['统一色彩', '完全停止', '无音高'], answer: 0 }],
  },

  {
    id: 'ritardando',
    category: '速度力度与表情',
    stage: 'primary-upper',
    level: 'L3',
    title: '渐慢',
    subtitle: 'rit.',
    concept: '渐慢表示速度逐渐放慢，常用于句尾或乐段结束前。',
    keyPoints: ['速度逐渐慢', '常在句尾出现', '制造收束感'],
    demo: 'tempo',
    quiz: [q('渐慢', '速度逐渐放慢', '音高升高', '力度增强'), { q: 'rit. 常表示？', options: ['渐慢', '渐强', '升号'], answer: 0 }],
  },
  {
    id: 'accelerando',
    category: '速度力度与表情',
    stage: 'junior-basic',
    level: 'L4',
    title: '渐快',
    subtitle: 'accel.',
    concept: '渐快表示速度逐渐加快，能制造推动和兴奋感。',
    keyPoints: ['速度逐渐快', '推动情绪', '不能失去稳定脉搏'],
    demo: 'tempo',
    quiz: [q('渐快', '速度逐渐加快', '调号变化', '歌词省略'), { q: 'accel. 常表示？', options: ['渐快', '渐弱', '还原'], answer: 0 }],
  },
  {
    id: 'tenuto',
    category: '速度力度与表情',
    stage: 'junior-basic',
    level: 'L4',
    title: '保持音',
    subtitle: 'tenuto',
    concept: '保持音提示该音要充分保持，不要过早收掉。',
    keyPoints: ['声音保持充分', '常用短横线表示', '和跳音形成对比'],
    demo: 'articulation',
    quiz: [q('保持音', '充分保持', '短促弹起', '完全休止'), { q: 'tenuto 更接近？', options: ['保持充分', '极短跳音', '拍号'], answer: 0 }],
  },
  {
    id: 'sforzando',
    category: '速度力度与表情',
    stage: 'junior-advanced',
    level: 'L5',
    title: '突强',
    subtitle: 'sfz',
    concept: '突强表示某个音突然强调，常带来戏剧性。',
    keyPoints: ['瞬间强调', '不是持续强', '制造戏剧性'],
    demo: 'dynamics',
    quiz: [q('突强', '瞬间强调', '渐渐变慢', '同音重复'), { q: 'sfz 通常表示？', options: ['突强', '渐弱', '低音谱号'], answer: 0 }],
  },
  {
    id: 'ornaments-intro',
    category: '速度力度与表情',
    stage: 'junior-advanced',
    level: 'L5',
    title: '装饰音入门',
    subtitle: '倚音、颤音、回音',
    concept: '装饰音用较小的音型装点主音，让旋律更精致。',
    keyPoints: ['装点主音', '不能盖过旋律', '风格差异明显'],
    demo: 'articulation',
    quiz: [q('装饰音', '装点主音', '确定拍号', '改变谱号'), { q: '装饰音应该服务于？', options: ['旋律表达', '删除主题', '只显示颜色'], answer: 0 }],
  },
  {
    id: 'breath-mark',
    category: '速度力度与表情',
    stage: 'primary-middle',
    level: 'L2',
    title: '换气记号',
    subtitle: '歌唱与吹奏的呼吸',
    concept: '换气记号提示歌唱或吹奏时的呼吸位置，帮助乐句自然。',
    keyPoints: ['提示呼吸', '服务乐句', '不要打断意思'],
    demo: 'form',
    quiz: [q('换气记号', '呼吸位置', '升降号', '和弦根音'), { q: '换气应该服务于？', options: ['乐句自然', '随机停顿', '删除歌词'], answer: 0 }],
  },

  {
    id: 'period-form',
    category: '曲式结构',
    stage: 'junior-basic',
    level: 'L4',
    title: '乐段',
    subtitle: '由多个乐句组成',
    concept: '乐段通常由若干乐句组成，形成较完整的音乐意思。',
    keyPoints: ['比乐句更大', '常有开始和结束', '可包含问答关系'],
    demo: 'form',
    quiz: [q('乐段', '多个乐句组成', '单个音符', '力度等级'), { q: '乐段通常比乐句？', options: ['更大', '更短', '无关'], answer: 0 }],
  },
  {
    id: 'rondo-form',
    category: '曲式结构',
    stage: 'junior-advanced',
    level: 'L5',
    title: '回旋曲式',
    subtitle: 'A 不断回来',
    concept: '回旋曲式中主部 A 多次回归，中间穿插不同插部。',
    keyPoints: ['A 多次回归', '插部形成对比', '结构记忆清晰'],
    demo: 'form',
    quiz: [q('回旋曲式', '主部反复回归', '只唱一次', '没有段落'), { q: '回旋曲式中常回来的段落是？', options: ['A', '最后一页', '谱号'], answer: 0 }],
  },
  {
    id: 'theme-development',
    category: '曲式结构',
    stage: 'junior-advanced',
    level: 'L5',
    title: '主题展开',
    subtitle: '主题材料的发展',
    concept: '主题展开通过重复、模进、节奏变化、转调等方式发展主题。',
    keyPoints: ['保留主题特征', '用变化推动', '形成更大结构'],
    demo: 'form',
    quiz: [q('主题展开', '发展主题材料', '删除节奏', '只换颜色'), { q: '主题展开要保留？', options: ['主题特征', '所有错误', '页面宽度'], answer: 0 }],
  },
  {
    id: 'intro-coda',
    category: '曲式结构',
    stage: 'primary-upper',
    level: 'L3',
    title: '引子与尾声',
    subtitle: '开始前和结束后',
    concept: '引子引入情绪或材料，尾声加强结束感。',
    keyPoints: ['引子铺垫开始', '尾声强化结束', '不一定每首都有'],
    demo: 'repeat',
    quiz: [q('引子与尾声', '开头铺垫和结尾收束', '音高单位', '力度缩写'), { q: '尾声常用来？', options: ['强化结束', '取消主题', '改变学生'], answer: 0 }],
  },
  {
    id: 'call-response',
    category: '曲式结构',
    stage: 'primary-middle',
    level: 'L2',
    title: '呼应结构',
    subtitle: '一句问一句答',
    concept: '呼应结构让音乐像对话一样，一句发起，另一句回应。',
    keyPoints: ['前后对话', '常用于民歌', '适合课堂接龙'],
    demo: 'form',
    quiz: [q('呼应结构', '前后对话', '和弦转位', '速度单位'), { q: '呼应结构像什么？', options: ['问答对话', '随机噪音', '只看谱号'], answer: 0 }],
  },
  {
    id: 'contrast-repetition',
    category: '曲式结构',
    stage: 'primary-upper',
    level: 'L3',
    title: '重复与对比',
    subtitle: '熟悉和新鲜',
    concept: '重复让音乐容易记住，对比带来新鲜感，两者共同塑造结构。',
    keyPoints: ['重复带来记忆', '对比带来变化', '平衡两者最自然'],
    demo: 'repeat',
    quiz: [q('重复与对比', '结构中的熟悉和变化', '音名数量', '谱号方向'), { q: '重复的作用是？', options: ['帮助记忆', '删除主题', '取消节拍'], answer: 0 }],
  },

  {
    id: 'rhythm-composition',
    category: '创作与编配',
    stage: 'primary-middle',
    level: 'L2',
    title: '节奏创编',
    subtitle: '用一小节开始创作',
    concept: '节奏创编可以从一小节开始，先稳定，再变化。',
    keyPoints: ['先有稳定拍', '再换节奏型', '最后连成句子'],
    demo: 'meter',
    quiz: [q('节奏创编', '设计节奏型', '背诵调号', '删除小节线'), { q: '创编节奏最好先保证？', options: ['稳定拍', '页面颜色', '歌词长度'], answer: 0 }],
  },
  {
    id: 'melody-ending',
    category: '创作与编配',
    stage: 'primary-upper',
    level: 'L3',
    title: '旋律结尾',
    subtitle: '停在稳定音',
    concept: '旋律结尾常回到稳定音，让听众感到完整。',
    keyPoints: ['句尾要收束', '稳定音带来结束感', '不同结尾有不同感觉'],
    demo: 'scale',
    quiz: [q('旋律结尾', '收束和稳定', '速度变快', '音色分类'), { q: '稳定结尾常带来？', options: ['完整感', '未完成感', '无声'], answer: 0 }],
  },
  {
    id: 'question-answer-writing',
    category: '创作与编配',
    stage: 'primary-upper',
    level: 'L3',
    title: '问答句写作',
    subtitle: '前句提问后句回答',
    concept: '问答句写作让短旋律更像有意思的话语。',
    keyPoints: ['前句可上扬', '后句可收束', '节奏可呼应'],
    demo: 'form',
    quiz: [q('问答句写作', '前后呼应', '只写和弦', '删除休止'), { q: '后句常需要？', options: ['回答和收束', '完全随机', '只升高'], answer: 0 }],
  },
  {
    id: 'ostinato',
    category: '创作与编配',
    stage: 'junior-basic',
    level: 'L4',
    title: '固定音型',
    subtitle: '反复出现的伴奏材料',
    concept: '固定音型通过不断重复形成稳定背景，是编配和课堂合奏常用方法。',
    keyPoints: ['材料反复', '形成背景', '适合合奏分层'],
    demo: 'repeat',
    quiz: [q('固定音型', '反复伴奏材料', '只唱主旋律', '删除低音'), { q: '固定音型常用于？', options: ['伴奏背景', '谱号命名', '音高单位'], answer: 0 }],
  },
  {
    id: 'countermelody',
    category: '创作与编配',
    stage: 'junior-advanced',
    level: 'L5',
    title: '副旋律',
    subtitle: '支持主旋律的第二线条',
    concept: '副旋律在不抢主旋律的前提下补充音乐层次。',
    keyPoints: ['支持主旋律', '避免抢戏', '形成层次'],
    demo: 'chord',
    quiz: [q('副旋律', '第二旋律线条', '拍号下方数字', '力度缩写'), { q: '副旋律应该？', options: ['支持主旋律', '完全盖住主旋律', '取消节奏'], answer: 0 }],
  },
  {
    id: 'arrangement-color',
    category: '创作与编配',
    stage: 'junior-basic',
    level: 'L4',
    title: '配器色彩',
    subtitle: '选择合适音色',
    concept: '配器色彩来自不同乐器和音区的组合，会影响音乐气质。',
    keyPoints: ['音色影响气质', '音区要平衡', '不要盖过主线'],
    demo: 'dynamics',
    quiz: [q('配器色彩', '音色和音区选择', '题目答案', '谱纸尺寸'), { q: '配器时主旋律应该？', options: ['清楚可听', '被盖住', '不存在'], answer: 0 }],
  },

  {
    id: 'folk-song-region',
    category: '民族与课堂常识',
    stage: 'primary-upper',
    level: 'L3',
    title: '民歌地域风格',
    subtitle: '不同地区不同味道',
    concept: '不同地区的民歌在语言、音调、节奏和演唱方式上都有特色。',
    keyPoints: ['语言影响旋律', '地域形成风格', '听赏要结合文化'],
    demo: 'scale',
    quiz: [q('民歌地域风格', '地区文化特色', '按钮大小', '文件名'), { q: '民歌风格常受什么影响？', options: ['地域文化', '页面宽度', '题库格式'], answer: 0 }],
  },
  {
    id: 'opera-role-types',
    category: '民族与课堂常识',
    stage: 'junior-basic',
    level: 'L4',
    title: '戏曲行当',
    subtitle: '生旦净丑',
    concept: '生旦净丑是中国戏曲常见行当，代表不同角色类型。',
    keyPoints: ['生多为男性角色', '旦多为女性角色', '净和丑有鲜明造型'],
    demo: 'dynamics',
    quiz: [q('戏曲行当', '角色类型', '拍号组合', '调号增减'), { q: '生旦净丑属于？', options: ['戏曲行当', '和弦名称', '节奏型'], answer: 0 }],
  },
  {
    id: 'world-music-meter',
    category: '民族与课堂常识',
    stage: 'junior-advanced',
    level: 'L5',
    title: '世界音乐节拍',
    subtitle: '不同文化的律动',
    concept: '不同文化有不同律动方式，音乐学习可以从拍子、乐器和场景比较。',
    keyPoints: ['节拍体现文化', '乐器组合不同', '听赏要开放比较'],
    demo: 'meter',
    quiz: [q('世界音乐节拍', '文化中的律动', '谱号字体', '按钮顺序'), { q: '比较世界音乐可先听？', options: ['节拍律动', '文件路径', '题目数量'], answer: 0 }],
  },
  {
    id: 'orchestra-sections',
    category: '民族与课堂常识',
    stage: 'primary-upper',
    level: 'L3',
    title: '管弦乐队声部',
    subtitle: '弦木铜打',
    concept: '管弦乐队常由弦乐、木管、铜管和打击乐等声部组成。',
    keyPoints: ['弦乐人数多', '木管音色丰富', '铜管和打击有力量'],
    demo: 'dynamics',
    quiz: [q('管弦乐队声部', '乐器家族分组', '唱名数字', '曲式结尾'), { q: '管弦乐队常见声部不包括？', options: ['页面声部', '弦乐声部', '木管声部'], answer: 0 }],
  },
  {
    id: 'listening-map',
    category: '民族与课堂常识',
    stage: 'junior-basic',
    level: 'L4',
    title: '听赏地图',
    subtitle: '用图记录音乐变化',
    concept: '听赏地图用线条、图形或关键词记录音乐中的段落、力度和情绪变化。',
    keyPoints: ['记录段落变化', '标出情绪走向', '帮助表达听感'],
    demo: 'form',
    quiz: [q('听赏地图', '记录音乐变化', '修改代码', '删除旋律'), { q: '听赏地图帮助学生？', options: ['表达听感', '跳过聆听', '只背答案'], answer: 0 }],
  },
  {
    id: 'classroom-ensemble-rules',
    category: '民族与课堂常识',
    stage: 'primary-middle',
    level: 'L2',
    title: '课堂合奏规则',
    subtitle: '听指挥、看同伴、守节拍',
    concept: '课堂合奏需要共同规则：听指挥、看同伴、守节拍、控制音量。',
    keyPoints: ['听指挥进入', '看同伴配合', '音量不盖主线'],
    demo: 'meter',
    quiz: [q('课堂合奏规则', '合作与节拍', '调号排序', '和弦转位'), { q: '合奏时最重要的是？', options: ['合作聆听', '各弹各的', '只追求大声'], answer: 0 }],
  },
]

export const EXPANDED_THEORY_TOPICS: TheoryTopic[] = drafts.map(makeTopic)
